services:

  rabbitmq:
    image: rabbitmq:3.9.16-management-alpine
    container_name: 'gaas-rabbitmq'
    restart: 'always'
    environment:
      - HOSTNAME=rabbitmq
      - RABBITMQ_NODENAME=node@rabbitmq
    volumes:
      - ./rabbitmq/conf/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - rabbitmq:/var/lib/rabbitmq/
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbitmq-net

  gaas-fleet-manager:
      image: gaas-docker-fleet-manager:latest
      build:
        context: .
        dockerfile: fleetmanager-js/Dockerfile
        ssh:
        - default
      container_name: gaas-fleet-manager
      env_file:
      - .env
      restart: always
      volumes:
        - ~/log/fleet-manager:/root/log
      networks:
      - rabbitmq-net

  gaas-ui:
      image: gaas-docker-ui:latest
      build:
        context: .
        dockerfile: interfaz/Dockerfile
        ssh:
        - default
      container_name: gaas-ui
      env_file:
      - .env
      restart: always
      ports:
        - 3000:3000
      volumes:
        - ~/log/interfaz:/root/log
      networks:
      - rabbitmq-net

  gaas-titan:
    build:
      context: .
      dockerfile: mavlinkuavpy/Dockerfile
      ssh:
        - default
    container_name: gaas-titan
    image: vehicle
    env_file:
      - .env
    environment:
      DEVICE_ID: titan
      LAT: 36.73635215795612
      LON: -4.735480570940837
    restart: always
    networks:
      - rabbitmq-net

  gaas-nostromo:
    build:
      context: .
      dockerfile: mavlinkuavpy/Dockerfile
      ssh:
        - default
    container_name: gaas-nostromo
    image: vehicle
    env_file:
      - .env
    environment:
      DEVICE_ID: nostromo
      LAT: 36.7361443663702
      LON: -4.735151560244702
    restart: always
    networks:
      - rabbitmq-net
  
  gaas-nebuchadnezzar:
    build:
      context: .
      dockerfile: mavlinkuavpy/Dockerfile
      ssh:
        - default
    container_name: gaas-nebuchadnezzar
    image: vehicle
    env_file:
      - .env
    environment:
      DEVICE_ID: nebuchadnezzar
      LAT: 36.735884189557225
      LON: -4.734648239245928
    restart: always
    networks:
      - rabbitmq-net

networks:
  rabbitmq-net:
    driver: bridge

volumes:
  rabbitmq:
